contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6b4b0439-9850-42d0-84e4-e39ccd8ac266
inputs: []
name: DSIS - SK - Playbook_v.1.1
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f01c9937-e57c-47e5-820c-d9dd79cc6830
      iscommand: false
      name: ""
      version: -1
    taskid: f01c9937-e57c-47e5-820c-d9dd79cc6830
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f88cbb15-f195-4560-8bb3-d52afbcf883c
      iscommand: false
      name: STOP
      type: title
      version: -1
    taskid: f88cbb15-f195-4560-8bb3-d52afbcf883c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 215,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
