contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 6b4b0439-9850-42d0-84e4-e39ccd8ac266
inputs: []
name: DSIS - SK - Playbook_v.1.1
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f01c9937-e57c-47e5-820c-d9dd79cc6830
      iscommand: false
      name: ""
      version: -1
    taskid: f01c9937-e57c-47e5-820c-d9dd79cc6830
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f88cbb15-f195-4560-8bb3-d52afbcf883c
      iscommand: false
      name: STOP
      type: title
      version: -1
    taskid: f88cbb15-f195-4560-8bb3-d52afbcf883c
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 380,
          "y": 630
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: test
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: f5625317-2566-44c0-88c4-08ddef788097
      iscommand: false
      name: print
      script: Print
      type: regular
      version: -1
    taskid: f5625317-2566-44c0-88c4-08ddef788097
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 330,
          "y": 250
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: test2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: a7355af4-de5f-4993-87b8-8b43df6c11a3
      iscommand: false
      name: test ajah
      script: Print
      type: regular
      version: -1
    taskid: a7355af4-de5f-4993-87b8-8b43df6c11a3
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 330,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 645,
        "width": 500,
        "x": 330,
        "y": 50
      }
    }
  }
